/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnavailableRouteImport } from './routes/unavailable'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSectionSlugPageSlugRouteImport } from './routes/docs.$sectionSlug.$pageSlug'

const UnavailableRoute = UnavailableRouteImport.update({
  id: '/unavailable',
  path: '/unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSectionSlugPageSlugRoute = DocsSectionSlugPageSlugRouteImport.update({
  id: '/docs/$sectionSlug/$pageSlug',
  path: '/docs/$sectionSlug/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/unavailable': typeof UnavailableRoute
  '/docs/$sectionSlug/$pageSlug': typeof DocsSectionSlugPageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/unavailable': typeof UnavailableRoute
  '/docs/$sectionSlug/$pageSlug': typeof DocsSectionSlugPageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/unavailable': typeof UnavailableRoute
  '/docs/$sectionSlug/$pageSlug': typeof DocsSectionSlugPageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loading' | '/unavailable' | '/docs/$sectionSlug/$pageSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loading' | '/unavailable' | '/docs/$sectionSlug/$pageSlug'
  id:
    | '__root__'
    | '/'
    | '/loading'
    | '/unavailable'
    | '/docs/$sectionSlug/$pageSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadingRoute: typeof LoadingRoute
  UnavailableRoute: typeof UnavailableRoute
  DocsSectionSlugPageSlugRoute: typeof DocsSectionSlugPageSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unavailable': {
      id: '/unavailable'
      path: '/unavailable'
      fullPath: '/unavailable'
      preLoaderRoute: typeof UnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$sectionSlug/$pageSlug': {
      id: '/docs/$sectionSlug/$pageSlug'
      path: '/docs/$sectionSlug/$pageSlug'
      fullPath: '/docs/$sectionSlug/$pageSlug'
      preLoaderRoute: typeof DocsSectionSlugPageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadingRoute: LoadingRoute,
  UnavailableRoute: UnavailableRoute,
  DocsSectionSlugPageSlugRoute: DocsSectionSlugPageSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
