export const RESERVED_USERNAMES = [
  "admin",
  "administrator",
  "support",
  "security",
  "mytuums",
  "mytuumsadmin",
  "staff",
  "moderator",
  "mod",
  "system",
  "root",
  "api",
  "help",
  "contact",
  "about",
  "terms",
  "privacy",
  "cookies",
  "accessibility",
  "login",
  "register",
  "logout",
  "settings",
  "notifications",
  "discover",
  "following",
  "home",
  "feed",
  "post",
  "search",
  "game",
  "games",
  "report",
  "reports",
  "block",
  "blocks",
  "owner",
  "founder",
  "ceo",
  "official",
  "verified",
  "team",
  "dev",
  "developer",
  "null",
  "undefined",
  "true",
  "false",
  "everyone",
  "all",
  "here",
  "anonymous",
  "unknown",
  "deleted",
  "removed",
  "suspended",
] as const

const RESERVED_USERNAME_SET = new Set<string>(RESERVED_USERNAMES)

export function isReservedUsername(username: string): boolean {
  return RESERVED_USERNAME_SET.has(username.trim().toLowerCase())
}
